### ISSUE TITLE
Post build event fails with MSBuild v4 in Build-WSPs script on machine lacking VS2012

### ISSUE THREAD

**Issue by softwarecraft** [glapointe/PowerShell-SPCmdlets#1]
My dev machine has VS2013 and not VS2012. When I run Build-WSPs.ps1 I get an error on the post build event:

> C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v11.0\SharePointTools\Mic
> rosoft.VisualStudio.SharePoint.targets(244,5): error : Could not load file or a
> ssembly 'Microsoft.VisualStudio.Modeling.Sdk.11.0, Version=11.0.0.0, Culture=ne
> utral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system
> cannot find the file specified. [C:\Projects\Repos\Lapointe\PowerShell-SPCmdlet
> s\Lapointe.SharePoint2013.PowerShell\Lapointe.SharePoint2013.PowerShell.csproj]

The issue and fix (switch to MSBuild v12) is described in various blog posts, eg [Changes In MSBuild with Visual Studio 2013](http://blog.maskalik.com/msbuild/2014/03/04/changes-in-msbuild-with-visual-studio-2013/).

If you want Build-WSPs to have the flexibility of using the appropriate version of MSBuild you could detect VS2013, eg:

``` powershell
function Get-MSBuildPath {
    # By default PowerShell does not have HKEY_CLASSES_ROOT defined so we have to define it
    if ($(Get-PSDrive HKCR -ErrorAction SilentlyContinue) -eq $null) {New-PSDrive -Name HKCR -PSProvider Registry -Root HKEY_CLASSES_ROOT > $null}

    if (Test-Path HKCR:\VisualStudio.DTE.12.0) {"C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe"} else {"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe"}
}
#$msbuild = "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe"
#$msbuild = "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe"
$msbuild = Get-MSBuildPath
```

If this approach suits you, I will submit a pull request.

**Comment by glapointe** [comment]
Works for me. I haven't done too much testing with this script as it's just something I threw together quickly one day so that I didn't have to manually build each target. Most people will likely just be building the one target they need for their environment but I'm all for improving the script to make it more flexible.

**Comment by glapointe** [comment]
I've updated the build script with the suggested function.
